# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mosquito-alert-2023',
                'doc_host': 'https://jmelsbach.github.io',
                'git_url': 'https://github.com/jmelsbach/mosquito-alert-2023',
                'lib_path': 'mosquito_alert_2023'},
  'syms': {'mosquito_alert_2023.core': {'mosquito_alert_2023.core.foo': ('core.html#foo', 'mosquito_alert_2023/core.py')}}}
